### PR TITLE
Code Organization

### PR DESCRIPTION
**Pull request by rweq1212**
1. edit main.cpp

2. add bmp_main.cpp, bmp_main.h

divide main.cpp into bmp_main.cpp and bmp_main.h

### CODE REVIEW

**Comment by sewonkimm** [comment]
console window doesn't appear ....

**Comment by sewonkimm** [comment]
Checked! No problem.
Go to merge.

**Comment by rooriririroo** [comment]
oh, it works well!!
It's much simpler than the old one
Go to merge~~

**Comment by JaVashit** [comment]
I also checked it. It is simpler than the previous codes.
If anyone doesn't reject to merge these codes, this request will be approve

**Comment by jej4480** [comment]
Cheked too. it seems fine to everyone. good job!

**Pull request merged**
