### PR TITLE
add print video

### PR DESCRIPTION
**Pull request by rweq1212**
add print video and save

1. create button2 
2. copy comment code

### CODE REVIEW

**Comment by sewonkimm** [comment]
Checked! Success Video conversion.
At GUIDlg.cpp deleted unnecessary parts(MFC event parts) and deleted Annotations.

I think we can delete edit_print_image branch.

**Comment by sewonkimm** [comment]
Maked header, check please.

**Comment by jej4480** [comment]
Checked.  I think It works well.

**Comment by rooriririroo** [comment]
Amazing! go to merge

**Comment by rweq1212** [comment]
nice~

**Pull request closed without merging**
